import logging

import pandas as pd
from fuzzywuzzy import fuzz

logger = logging.getLogger(__name__)
STRING_REPLACE_MAP = {"č": "c", "ć": "c", "š": "s", "ž": "z", "đ": "d", " ": ""}


def preprocess_string(s: str):
    """Preprocess a string.

    Args:
        s: The string to preprocess

    Returns:
        The preprocessed string

    !!! note

        The above docstring is autogenerated by docstring-gen library (https://docstring-gen.airt.ai)
    """
    s = s.lower()
    for old, new in STRING_REPLACE_MAP.items():
        s = s.replace(old, new)
    return s


def match_strings(s1: str, s2: str, string_metric: callable = fuzz.ratio) -> float:
    """Match two strings

    Args:
        s1: First string
        s2: Second string
        string_metric: A callable that takes two strings and returns a float

    Returns:
        The distance between the two strings

    !!! note

        The above docstring is autogenerated by docstring-gen library (https://docstring-gen.airt.ai)
    """
    s1 = preprocess_string(s1)
    s2 = preprocess_string(s2)
    string_distance = string_metric(s1, s2)
    return string_distance


def match_form_with_sheet(
    form_df: pd.DataFrame, sheet_df: pd.DataFrame, columns_join_map: dict[str:str]
) -> dict[tuple:tuple]:
    """Match rows in a form with rows in a sheet.

    Args:
        form_df: Dataframe of the form
        sheet_df: Dataframe of the sheet
        columns_join_map: A dictionary mapping columns in the form to columns in the sheet.

    Returns:
        A dictionary mapping rows in the sheet to rows in the form.

    !!! note

        The above docstring is autogenerated by docstring-gen library (https://docstring-gen.airt.ai)
    """
    matched_row_map = {}
    form_cols = columns_join_map.keys()
    sheet_cols = columns_join_map.values()
    for sheet_row in sheet_df[sheet_cols].values:
        max_score = 0
        max_score_form_row = None
        for form_row in form_df[form_cols].values:
            # If already matched
            if tuple(form_row) in matched_row_map.values():
                continue
            total_score = 0
            # Calculate string similarity metric for every column, add to total score
            for form_val, sheet_val in zip(form_row, sheet_row):
                cur_match = match_strings(form_val, sheet_val)
                total_score += cur_match
            # If the score is max, match rows
            if total_score >= max_score:
                max_score = total_score
                max_score_form_row = form_row
        matched_form_row = tuple(max_score_form_row)
        # Allow 10% difference between each string
        # TODO: make the limit configurable. Optionally match each string individually
        if max_score < 90 * len(sheet_cols):
            logger.warning(
                f"Weak match [{max_score / len(sheet_cols)}%] between existing sheet row and best form response match: "
                f"<SHEET> {sheet_row}: <FORM> {max_score_form_row}. This row was skipped."
            )
            matched_form_row = None
        matched_row_map[tuple(sheet_row)] = matched_form_row
    return matched_row_map


def compute_target_col(
    form_df: pd.DataFrame,
    sheet_df: pd.DataFrame,
    transfer_function: callable,
    match_col_form_name_to_sheet_name_map: dict[str:str],
) -> list:
    """Compute a new column for the sheet based on the form.

    Args:
        form_df: The form dataframe
        sheet_df: The sheet dataframe
        transfer_function: The function to compute the new column
        match_col_form_name_to_sheet_name_map: A dictionary mapping form columns to sheet columns

    Returns:
        The new column

    !!! note

        The above docstring is autogenerated by docstring-gen library (https://docstring-gen.airt.ai)
    """
    sheet_id_cols = match_col_form_name_to_sheet_name_map.values()
    # Which form questions were matched to which sheet columns
    row_match_dict = match_form_with_sheet(
        form_df, sheet_df, match_col_form_name_to_sheet_name_map
    )
    # Compute new col from form
    new_col_df = transfer_function(form_df)
    # Sort new col by position in sheet
    new_col = []
    for sheet_row in sheet_df[sheet_id_cols].values:
        matched_form_row = row_match_dict[tuple(sheet_row)]
        # If no response was found in forms
        if matched_form_row is None:
            new_col.append(
                "Unknown (report is missing)"
            )  # TODO: ADD MESSAGE AS PARAMETER
            continue
        # Get the target which was matched with sheet row
        pandas_subqueries = [
            "`" + form_question + "`" + "==" + '"' + form_answer + '"'
            for form_question, form_answer in zip(
                match_col_form_name_to_sheet_name_map.keys(), matched_form_row
            )
        ]
        pandas_query = " and ".join(pandas_subqueries)
        df = new_col_df.query(pandas_query)
        target = df.target.values[0]
        new_col.append(target)
    return new_col
