import logging
import os
from typing import Optional

from google_data_transfer.commons import PathType
from google_data_transfer.controller.data_transfer import compute_target_col
from google_data_transfer.google_api.form import Form
from google_data_transfer.google_api.sheet import Sheet
from google_data_transfer.transfer_configs.transfer_config import TransferConfig

logger = logging.getLogger(__name__)


def transfer_form_responses_to_sheet(
    form: Form, sheet: Sheet, transfer_config: TransferConfig
) -> None:
    """Transfer responses from a form to a sheet.

    Args:
        form: The form to transfer responses from.
        sheet: The sheet to transfer responses to.
        transfer_config: The transfer configuration.

    Returns:
        None

    !!! note

        The above docstring is autogenerated by docstring-gen library (https://docstring-gen.airt.ai)
    """

    new_col = compute_target_col(
        form,
        sheet,
        transfer_config
    )
    sheet.write_col(transfer_config.target_col, new_col)


def save_google_data(
    form: Form,
    sheet: Sheet,
    form_save_path: Optional[PathType] = None,
    sheet_save_path: Optional[PathType] = None,
) -> None:
    """Save Google Form and Sheet data to disk.

    Args:
        form: The form to save
        sheet: The sheet to save
        form_save_path: The path to save the form data to
        sheet_save_path: The path to save the sheet data to

    Returns:
        None

    !!! note

        The above docstring is autogenerated by docstring-gen library (https://docstring-gen.airt.ai)
    """
    sheet_df = sheet.to_df()
    form_df = form.to_df()

    if sheet_save_path is not None:
        os.makedirs(sheet_save_path, exist_ok=True)
        sheets_save_path = os.path.join(
            sheet_save_path, f"{sheet.spreadsheet_id}_{sheet.name}.csv"
        )
        sheet_df.to_csv(sheets_save_path)
        logger.info(f"Saved {sheet.spreadsheet_id}, {sheet.name} to {sheets_save_path}")

    if form_save_path is not None:
        os.makedirs(form_save_path, exist_ok=True)
        save_path = os.path.join(form_save_path, f"{form.id}.csv")
        form_df.to_csv(save_path)
        logger.info(f"Saved {form.id} to {save_path}")
