import os.path

from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow

from google_data_transfer.commons import PathType


def authenticate_google_api(
        creds_path: PathType, creds_token_path: PathType, scopes: tuple[str]
) -> Credentials:
    """Authenticate with Google API

    Args:
        creds_path: Path to the credentials file
        creds_token_path: Path to the credentials token file
        scopes: List of scopes

    Returns:
        The credentials

    !!! note

        The above docstring is autogenerated by docstring-gen library (https://docstring-gen.airt.ai)
    """
    creds = None
    # The file token.json stores the user's access and refresh tokens, and is
    # created automatically when the authorization flow completes for the first
    # time.
    if os.path.exists(creds_token_path):
        creds = Credentials.from_authorized_user_file(creds_token_path, scopes)
    # If there are no (valid) credentials available, let the user log in.
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(creds_path, scopes)
            creds = flow.run_local_server(port=0)
        # Save the credentials for the next run
        with open(creds_token_path, "w") as token:
            token.write(creds.to_json())
    return creds


def authenticate_google_api_st(
        json_token, scopes: tuple[str]
) -> Credentials:
    """Authenticate with Google API

    Args:
        json_token: Authorization token
        scopes: List of scopes

    Returns:
        The credentials

    !!! note

        The above docstring is autogenerated by docstring-gen library (https://docstring-gen.airt.ai)
    """
    creds = Credentials.from_authorized_user_info(json_token, scopes)
    return creds
