from abc import ABC, abstractmethod
from dataclasses import dataclass

import pandas as pd


@dataclass
class TransferConfig(ABC):
    match_col_form_name_to_sheet_name_map: dict[str:str]
    target_col: str
    name: str

    def __init__(
        self,
        match_col_form_name_to_sheet_name_map: dict[str:str],
        target_col: str,
        name: str,
    ):
        """A class to represent a person.

        Attributes:
            match_col_form_name_to_sheet_name_map : a dictionary mapping the columns to join
            target_col : the target column
            name : the name of the person

        !!! note

            The above docstring is autogenerated by docstring-gen library (https://docstring-gen.airt.ai)
        """
        self.match_col_form_name_to_sheet_name_map = (
            match_col_form_name_to_sheet_name_map
        )
        self.target_col = target_col
        self.name = name

    @abstractmethod
    def transfer(self, df: pd.DataFrame, **kwargs) -> pd.DataFrame:
        ...
