import json
import os
import pathlib
from typing import Union


def jprint(dic):
    """Print a dictionary in a pretty way.

    Args:
        dic: The dictionary to print

    !!! note

        The above docstring is autogenerated by docstring-gen library (https://docstring-gen.airt.ai)
    """
    print(json.dumps(dic, indent=2))


# TODO: handle all path manipulations with pathlib
PathType = Union[str, os.PathLike, pathlib.Path]
