import os
from pathlib import Path

import gin
from google_data_transfer.commons import PathType
from google_data_transfer.data_transfer import compute_target_col
from google_data_transfer.google_api.form import Form, GoogleAPIForm
from google_data_transfer.google_api.google_connection import GoogleFormsConnection
from google_data_transfer.google_api.sheet import GSpreadSheet, Sheet
from google_data_transfer.transfer_configs.transfer_config import TransferConfig


@gin.configurable
def main(
    form_url: str,
    sheet_url: str,
    sheet_name: str,
    target_col: str,
    transfer_config_id: str,
    transfer_configs_path: PathType,
    creds_path: PathType,
    creds_token_path: PathType,
    google_api_scopes: list[str],
    save_data: bool = True,
):
    """Main function to transfer data from a Google Form to a Google Sheet.

    Args:
        form_url: URL of the Google Form
        sheet_url: URL of the Google Sheet
        sheet_name: Name of the Google Sheet
        target_col: Target column in the Google Sheet
        transfer_config_id: ID of the transfer configuration
        transfer_configs_path: Path to the transfer configurations
        creds_path: Path to the credentials
        creds_token_path: Path to the credentials token
        google_api_scopes: List of Google API scopes
        save_data: Whether to save the data

    !!! note

        The above docstring is autogenerated by docstring-gen library (https://docstring-gen.airt.ai)
    """
    pickle_config_path = Path(transfer_configs_path) / (transfer_config_id + ".pickle")
    transfer_config = TransferConfig.from_pickle(pickle_config_path)

    sheet = GSpreadSheet.from_creds_file(creds_path, sheet_url, sheet_name)
    form = GoogleAPIForm.from_creds_file(
        creds_path, creds_token_path, google_api_scopes, form_url
    )

    transfer_form_responses_to_sheet(form, sheet, target_col, transfer_config)
    # TODO: add logging
    print("Data transfer successful.")
    if save_data:
        save_google_data(form, sheet)


@gin.configurable
def save_google_data(
    form: Form,
    sheet: Sheet,
    forms_save_datapath: PathType = None,
    sheets_save_datapath: PathType = None,
) -> None:
    """Save Google Form and Sheet data to disk.

    Args:
        form: The form to save
        sheet: The sheet to save
        forms_save_datapath: The path to save the form data to
        sheets_save_datapath: The path to save the sheet data to

    Returns:
        None

    !!! note

        The above docstring is autogenerated by docstring-gen library (https://docstring-gen.airt.ai)
    """
    sheet_df = sheet.to_df()
    form_df = form.to_df()

    if sheets_save_datapath is not None:
        os.makedirs(sheets_save_datapath, exist_ok=True)
        sheets_save_path = os.path.join(
            sheets_save_datapath, f"{sheet.spreadsheet_id}_{sheet.name}.csv"
        )
        sheet_df.to_csv(sheets_save_path)
        print(f"Saved {sheet.spreadsheet_id}, {sheet.name} to {sheets_save_path}")

    if forms_save_datapath is not None:
        os.makedirs(forms_save_datapath, exist_ok=True)
        save_path = os.path.join(forms_save_datapath, f"{form.id}.csv")
        form_df.to_csv(save_path)
        print(f"Saved {form.id} to {save_path}")


def transfer_form_responses_to_sheet(
    form: Form, sheet: Sheet, target_col: str, transfer_config: TransferConfig
) -> None:
    """Transfer responses from a form to a sheet.

    Args:
        form: The form to transfer responses from.
        sheet: The sheet to transfer responses to.
        target_col: The column to transfer responses to.
        transfer_config: The transfer configuration.

    Returns:
        None

    !!! note

        The above docstring is autogenerated by docstring-gen library (https://docstring-gen.airt.ai)
    """
    form_df = form.to_df()
    sheet_df = sheet.to_df()
    new_col = compute_target_col(
        form_df,
        sheet_df,
        transfer_config.transfer_function,
        transfer_config.columns_join_map,
    )
    if target_col is None:
        target_col = transfer_config.target_col
    sheet.write_col(target_col, new_col)
