[installed]
installed.client_id = "351673575320-tm0fkd1ki758il38s8pj2bv34ofndlcn.apps.googleusercontent.com"
installed.project_id = "mentoring-reports-371613"
installed.auth_uri = "https://accounts.google.com/o/oauth2/auth"
installed.token_uri = "https://oauth2.googleapis.com/token"
installed.auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
installed.client_secret = "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"
installed.redirect_uris = [ "http://localhost" ]

[token]
token = "ya29.a0AfB_byAMw_iGWCMNBPf1UaW2Baw4MHG1g4OamMvQeB19tWVdenjK3rFDB96TiLiem8V-frKFM95hCgc6zLL6XMDv3pq0OeS4-0CatFox-3T2xXqdueg8J1RaeSxP6leKxWHlRa7KxQq-gS58VpQWTy8H5wPmblJvUb8hfZgaCgYKAeQSARISFQHGX2Mixg3GLABPpOodRevOYp-eHA0174"
refresh_token = "1//09Qce9yMuEkjTCgYIARAAGAkSNwF-L9IrELGJXnuvtHKUs31Ee2AKkmins2nQ7bkOLoiq9PiHWd4qufBKfJJWeuiYaBffc0_WKSY"
token_uri = "https://oauth2.googleapis.com/token"
client_id = "351673575320-tm0fkd1ki758il38s8pj2bv34ofndlcn.apps.googleusercontent.com"
client_secret = "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"
scopes = [
  "https://www.googleapis.com/auth/forms.body.readonly",
  "https://www.googleapis.com/auth/forms.body",
  "https://www.googleapis.com/auth/forms.responses.readonly",
  "https://www.googleapis.com/auth/drive",
  "https://www.googleapis.com/auth/drive.file",
  "https://www.googleapis.com/auth/drive.readonly",
  "https://www.googleapis.com/auth/spreadsheets.readonly"
]
universe_domain = "googleapis.com"
expiry = "2023-12-15T20:55:51.721179Z"
